<Project>
    <PropertyGroup>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <WarningLevel>10</WarningLevel>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <GenerateDependencyFile>false</GenerateDependencyFile>
        <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
    </PropertyGroup>

    <PropertyGroup>
        <VersionFile>$(MSBuildThisFileDirectory)../VERSION</VersionFile>
        <VersionFromFile Condition="Exists('$(VersionFile)')">$([System.IO.File]::ReadAllText('$(VersionFile)').Trim())</VersionFromFile>
        <Version Condition="'$(VersionFromFile)' != ''">$(VersionFromFile)</Version>
        <PackageVersion Condition="'$(VersionFromFile)' != ''">$(VersionFromFile)</PackageVersion>
        <AssemblyVersion Condition="'$(VersionFromFile)' != ''">$(VersionFromFile)</AssemblyVersion>
        <FileVersion Condition="'$(VersionFromFile)' != ''">$(VersionFromFile)</FileVersion>
        <PublishRelease>true</PublishRelease>
    </PropertyGroup>
</Project>
